name = "dr-mobiles-karaikal"
compatibility_date = "2026-05-25"
main = "src/worker.ts"

[assets]
directory = "./out"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "dr_mobiles_db"
database_id = "60b7c83f-ed1f-40a1-b8f1-4bb03cc9a525"
